declare const Services: any;
declare const Ci: any;
declare const Cc: any;
declare const Cr: any;
declare const Cu: any;
declare const ChromeUtils: any;
declare const IOUtils: any;
declare const Components: any;
declare const PathUtils: any;
