// This file was autogenerated by the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

import { UniFFITypeError } from "moz-src:///toolkit/components/uniffi-js/js/UniFFI.sys.mjs";

{% import "macros.sys.mjs" as js %}

// Objects intended to be used in the unit tests
export var UnitTestObjs = {};

{% include "Helpers.sys.mjs" %}

{% include "Types.sys.mjs" %}

{% include "TopLevelFunctions.sys.mjs" %}
